version: "3.12"

services:
  webapp:
    build: .
    container_name: todo-app
    ports:
      - "5000:5000"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    command: python app.py
